### ISSUE TITLE
Game Name wrong..

### ISSUE THREAD

**Issue by Jonny0r** [gibaBR/XCI-Organizer#3]
Hello,

First, thanks for your awesome tool, but the Game Names in the main Window are wrong (at my side). They are directly appear from the beginning with the "Detailed" Name. If i change to simple, nothing happens in this windows, but if you batch rename then he takes the correct Name.

Thank you :)

As a suggestion, would it not perhaps be possible to add a small picture of the game in the Main Window which is always shown, not only text, for sure smaller, perhaps with an on / off function :)

**Comment by StudentBlake** [comment]
Sorry, I don't quite understand what you mean by the game names are wrong. Would you take a picture? The Simple, Detailed, and Scene buttons are only for renaming as of right now. Also, the order will be incorrect if you use Detailed because it orders by file name alphabetically.

**Comment by Jonny0r** [comment]
![1](https://user-images.githubusercontent.com/3064788/42383248-01fd88f8-8137-11e8-9838-0dc51cc9d521.jpg)

Sorry, my english is perhaps not the best, its not my native leanguage. :) I mean this, your File Name is currently "xyz.xci" but the organizer shows up "xyz.xci (World) (Jap,Ru,Pl,Wtf)" also when you only press "simple" on "tools" it has no effect.

And for the suggestion i meant something like WBFS-Manager a bit..

Thansk for your time :)

**Comment by gibaBR** [comment]
OK, I got it. The name you see on your left is not the real rom name. It is just a composition of the game name + Region + Languages. It is just a way to display more information on the list. The Options you see on the right are for Renaming the Files. 
Both are independent.
As for the thumbnail image on the list, actualy I was thinking about that already but its not a priority right now.
